spec: "0.0"
name: blink
uuid: a80d7227-948c-4be7-a174-9fffdc3b1cbe
type: docker
onboot:
- name: hello-world
  uuid: 4499b8d5-f92e-4356-9348-219597babd98
  image: armhf/hello-world
  directory: ""
  net: ""
  pid: ""
  readonly: false
  command: []
  binds: []
  capabilities: []
services:
- name: blink
  uuid: 7b24b019-b212-4549-8eb1-f7cd7f9ab342
  image: ""
  directory: "."
  net: ""
  pid: ""
  readonly: false
  command: []
  binds: []
  capabilities: []
